steps:
  # Tek adimda kaynak koddan derleyip Cloud Run'a konuslandir.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'techfix'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'

# Sirket hesabindaki Log yetki sinirlandirmasini asmak icin loglamayi devre disi birakiyoruz
options:
  logging: 'NONE'
